### ISSUE TITLE
Authentication fails with digiromania.ro account

### ISSUE THREAD

**Issue by crisp2u** [dexterke/plugin.video.digi.ro-online#2]
I think the plugin is missing support for login with digiromania.ro account which is possible on the website. Is this correct ?

**Comment by dexterke** [comment]
Most likely there is an issue with the number of devices you've registered.
Possible reasons for not being able to login:

    1. Visit https://www.digiromania.ro/my-account/my-services  -> Digi Online -> Configureaza -> DISPOZITIVE CONECTATE and delete one or more of the devices listed there (You can have up to 5 devices registered per account)

   2. The plugin's auto-generated registration cookie has expired: Delete file YOUR_KODI_HOME/userdata/addon_data/plugin.video.digi.ro-online/digionline.ro.cookie
digionline.ro.cookie file had been generated when you accessed the plugin for the first time, there is no harm in deleting the file. YOUR_KODI_HOME  is documented on the Official KODI WIKI https://kodi.wiki/view/Userdata

**Comment by dexterke** [comment]
Q: 'I think the plugin is missing support for login with digiromania.ro account which is possible on the website. Is this correct ?'
A: Documented in Readme.md:  'User registration & login credentials are required in order to access digionline.ro media content. Visit https://www.digiromania.ro for more details.'
As far as the owner is aware the only way to use this plugin is to use correct login credentials, I can confirm the plugin is working correctly, login is support is working correctly. If you can't use the plugin, most likely the issue is the number of registered devices (You can have up to 5 devices registered per account).

Possible cause 1. Visit https://www.digiromania.ro/my-account/my-services -> Digi Online -> Configureaza -> DISPOZITIVE CONECTATE and delete one or more of the devices listed there

Possible cause 2. The plugin's auto-generated registration cookie has expired: Delete file YOUR_KODI_HOME/userdata/addon_data/plugin.video.digi.ro-online/digionline.ro.cookie
THe 'digionline.ro.cookie' file gets generated when the user tries to access the plugin for the first time, there is no harm in deleting it. YOUR_KODI_HOME is documented on the Official KODI WIKI https://kodi.wiki/view/Userdata

**Comment by crisp2u** [comment]
Thanks. Sorry but i'm a bit confused also by the new plugin name and how the credentials work. I ment that the plugin seems to accept a single set of credentials vs the digionline.ro which gives the user these options: 

![image](https://user-images.githubusercontent.com/651414/59842774-e08ca280-935f-11e9-93c3-db74f20e2725.png)

Anyway I'm using digiromania.ro credentials. I've checked the number of registered devices and there are only 2. 

I'll test also removing the cookie file later today. 

Thanks

**Comment by dexterke** [comment]
If playback works when using your browser, same credentials should work with Kodi. The kodi plugin is just a reverse-engineered hack that tries to emulate the browser behaviour. Device/account management (activation) is not supported by this plugin, DIGI online and DIGI accounts management are on different web sites
DIGI Online portal: https://www.digionline.ro/
DIGI accounts management:  https://www.digiromania.ro/my-account/my-services


---- Disclaimer ----
The author does not host or own any content found within this Addon. The author is not connected to or in any other way affiliated with Kodi, Team Kodi, the XBMC foundation, RCS RDS SA, digi24.ro or digionline.ro

Due to copyright and licensing reasons beyond the author's control, access to Digi-Online TV programmes may be subject to geoblocking (restricted access for viewers outside RCS-RDS Romania network).

User registration & login credentials are required in order to access digionline.ro media content. Visit https://www.digiromania.ro for more details.

**Comment by dexterke** [comment]
@crisp2u any updates?

**Comment by crisp2u** [comment]
@dexterke I'm sorry, I did not get a chance to test your solution. So here are my findings bellow:

* there is no cookie file in the userdata folder because I did not successfully logged in ever
* as I said in my previous comment the plugin seems to support only login with digionline account (i've put the wrong screenshot)

![image](https://user-images.githubusercontent.com/651414/60618491-fcbc2500-9dde-11e9-9425-1bc4b58e30b6.png)

* i don't have a digionline account so I choose the right side form. In the browser I enter my digi romania email and password and I log in
* i checked the debug log and you submit only the left form (action is `/auth/login`).
* on the right form the action is `/auth/login-digiro` and the fields are `form-login-digiro-email` and `form-login-digiro-password`

I hope this is more clear now. Depending on the time and my rusty python skills I might try to implement this :)

**Comment by dexterke** [comment]
See the other issue opened recently, sounds like the same problem
https://github.com/dexterke/plugin.video.digi.ro-online/issues/3
If so, your problem would be temporarily fixed there by Alex,  I'll merge the changes when I have some time.

**Comment by crisp2u** [comment]
Yeap, same thing. You can leave this closed and we track this in #3, but maybe change the title to be more accurate

**Comment by dexterke** [comment]
v 1.2.0 - Added support for DIGI-Romania acounts login
@crisp2u  please test and provide feedback.

**Comment by arkaddium** [comment]
> v 1.2.0 - Added support for DIGI-Romania acounts login
> @crisp2u please test and provide feedback.

no, it's stii not ok. the problem still the same at login.
what can be done? thnx!

**Comment by crisp2u** [comment]
I’ve bot used Kodi in a while but I remember being able to login, not sure if it was master branch or not. I’ll check again when I have some time

**Comment by arkaddium** [comment]
> I’ve not used Kodi in a while but I remember being able to login, not sure if it was master branch or not. I’ll check again when I have some time

Please!! Thanks a lot!

**Comment by arkaddium** [comment]
hello!! any news on this hot metter?
