### ISSUE TITLE
Support for DRM protected channels, HBO

### ISSUE THREAD

**Issue by mzsombor** [dexterke/plugin.video.digi.ro-online#5]
Hi @dexterke ,

First of all thank you for developing this plugin.
I saw an entry in the changelog saying that DRM protected channels are not supported yet.
Is it actually on the roadmap to develop this feature? Is it difficult/possible to even make this?
I could contribute to the development if you could offer some guidance.

**Comment by dexterke** [comment]
Hi  @mzsombor ,
I do not know much about DRM technology and at the time I had developed this plugin KODI was not supporting DRM anyway. This plugin was just a little side project that I wrote for fun, but decoding DRM was never in my scope, IMHO it just does not worth my while to do more work on this plugin, I will do my best to keep it updated but that is all I am committed to.

**Comment by cralin** [comment]
@dexterke,
Please accept my apologies for hijacking this thread.

@mzsombor,
I believe @dexterke made it clear in this thread as well as in [this](https://github.com/dexterke/plugin.video.digi.ro-online/issues/8) thread that he is not interested to invest time in implementing support for DRM content in his plugin.

Nevertheless, you're not the only one who wants/wanted to have a Kodi plugin that can also play the DRM content from the DigiOnline.ro.

Since I also wanted to have this functionality implemented, I've spent some of my free time working on a Kodi add-on that would play all the content available to me in my DigiOnline.ro account.

[This Kodi add-on](https://github.com/cralin/plugin.video.DigiOnline.ro) is now capable to play the DRM content from DigiOnline.ro (tested with Cinemax and Cinemax 2 channels) and is also building the list of channels dynamically based on what is available in the DigiOnline.ro account configured to be used by the add-on.

**Comment by dexterke** [comment]
Congrats @cralin , brilliantly executed - you're obviously a professional programmer :) Well done - Big kudos to you, thanks for chiming in.

**Comment by cralin** [comment]
@dexterke,
Thank you.

For the record:  I'm not really a developer. I'm an IT engineer and I wanted to solve one of my problems.

I still have more ideas for improvements to be implemented in [this Kodi addon](https://github.com/cralin/plugin.video.DigiOnline.ro) in order to bring it closer to a more polished state.

I hereby invite you (and anybody else interested and willing to help) to join forces and make [this Kodi addon](https://github.com/cralin/plugin.video.DigiOnline.ro) the add-on one wants to install and use with Kodi and DigiOnline.ro.

**Comment by mzsombor** [comment]
@cralin and @dexterke thanks guys for making this happen.
I was also planning to start developing something but never really made time for it. I'm not an expert either but I'm pretty sure we will be able to put something together.

@cralin I am unable to use your addon. For the time being I'm getting an empty screen with no errors after I open it, but I think I will move this topic to your project instead.

Again, thanks and nice work guys.
